<?php

namespace Hjolfaei\Todo;

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Request;
use \Illuminate\Support\ServiceProvider;

class TodoServiceProvider extends ServiceProvider
{

    public function boot(){

        //Loading routes,views, migrations ,factories
        $this->loadRoutesFrom(__DIR__.'/routes/web.php');
        $this->loadRoutesFrom(__DIR__.'/routes/api.php');
        $this->loadViewsFrom(__DIR__.'/views','hjolfaei');
        $this->loadMigrationsFrom(__DIR__.'/database/migrations');
        $this->loadFactoriesFrom(__DIR__.'/database/factories');




        //Adding middleware to kernel.php api section.
        $router = $this->app['router'];
        $router->pushMiddlewareToGroup('auth:custom', Http\Middleware\AuthKey::class);

    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }



}
